ASI.Basecode.WebApp/Controllers/ArticleController.cs
using ASI.Basecode.Services.Interfaces;
using ASI.Basecode.Services.ServiceModels;
using ASI.Basecode.Data.Models;
using ASI.Basecode.WebApp.Mvc;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System.Linq;
using System;
using System.IO;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using ASI.Basecode.Services.Services;
using ASI.Basecode.Data.Interfaces;
using Microsoft.AspNetCore.Authorization;



namespace ASI.Basecode.WebApp.Controllers
{
    public class ArticleController : ControllerBase<ArticleController>
    {

        private readonly IArticleService _articleService;
        private readonly IFavoriteRepository _favoriteRepository;
        private readonly ISessionHelper _sessionHelper;
        private readonly IUserRepository _userRepository;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="httpContextAccessor"></param>
        /// <param name="loggerFactory"></param>
        /// <param name="configuration"></param>
        /// <param name="localizer"></param>
        /// <param name="mapper"></param>
        public ArticleController(IArticleService articleService,
            IHttpContextAccessor httpContextAccessor,
                              ILoggerFactory loggerFactory,
                              IConfiguration configuration,
                              IFavoriteRepository favoriteRepository,
                              IUserRepository userRepository,
                              ISessionHelper sessionHelper,
                              IMapper mapper = null) : base(httpContextAccessor, loggerFactory, configuration, mapper)
        {
            _articleService = articleService;
            _favoriteRepository = favoriteRepository;
            _sessionHelper = sessionHelper;
            _userRepository = userRepository;
        }

        /// <summary>
        /// Returns Article View.
        /// </summary>
        /// <returns> Article View </returns>
        [HttpGet ("/KnowledgeBase")]
        public IActionResult Index(string searchString, string category)
        {
            var roleId = _userRepository.GetUsers().Where(u => u.UserId == _sessionHelper.GetUserIdFromSession()).FirstOrDefault().RoleId;
            ViewBag.RoleId = roleId;
            ViewBag.AdminSidebar = "Index";
            ViewBag.AgentSidebar = "Index";
            ViewBag.SearchString = searchString;
            ViewBag.CategoryString = category;
            ViewBag.FavoriteCount = _articleService.GetUserFavoriteCount();

            var data = _articleService.RetrieveAll()
                                        .Select(u => new ArticleViewModel
                                        {
                                            ArticleId = u.ArticleId,
                                            Title = u.Title,
                                            Body = u.Body,
                                            CategoryNavigation = u.CategoryNavigation,
                                            DateUpdated = u.DateUpdated,
                                        })
                                        .OrderBy(u => u.Title)
                                        .ToList();
            if (!String.IsNullOrEmpty(searchString)){
                data = _articleService.RetrieveAll()
                                        .Where(u =>  u.Title.Contains(searchString, StringComparison.OrdinalIgnoreCase))
                                        .Select(u => new ArticleViewModel
                                        {
                                            ArticleId = u.ArticleId,
                                            Title = u.Title,
                                            Body = u.Body,
                                            CategoryNavigation = u.CategoryNavigation,
                                            DateUpdated = u.DateUpdated,
                                        })
                                        .ToList();
            }
            
            if (category != "default")
            {
                if (!String.IsNullOrEmpty(category))
                {
                    data = _articleService.RetrieveAll()
                                            .Where(u => u.CategoryNavigation.Contains(category, StringComparison.OrdinalIgnoreCase))
                                            .Select(u => new ArticleViewModel
                                            {
                                                ArticleId = u.ArticleId,
                                                Title = u.Title,
                                                Body = u.Body,
                                                CategoryNavigation = u.CategoryNavigation,
                                                DateUpdated = u.DateUpdated,
                                            })
                                            .ToList();
                }
            }
            var viewModel = new ArticleViewModel
            {
                Articles = data,
            };
            return View(viewModel);
        }

        /// <summary>
        /// Returns Article Favorites View.
        /// </summary>
        /// <returns> Article Favorites View </returns>
        [HttpGet("/KnowledgeBase/MyFavorites")]
        public IActionResult MyFavorites(string searchString)
        {
            ViewBag.AdminSidebar = "Index";
            ViewBag.AgentSidebar = "Index";
            ViewBag.SearchString = searchString;
            ViewBag.RoleId = _userRepository.GetUsers().Where(u => u.UserId == _sessionHelper.GetUserIdFromSession()).FirstOrDefault().RoleId;
            ViewBag.FavoriteCount = _articleService.GetUserFavoriteCount();
            var data = _articleService.RetrieveFavorites()
                                        .Select(u => new ArticleViewModel
                                        {
                                            ArticleId = u.ArticleId,
                                            Title = u.Title,
                                            Body = u.Body,
                                            CategoryNavigation = u.CategoryNavigation,
                                            DateUpdated = u.DateUpdated,
                                        })
                                        .ToList();
            if (!String.IsNullOrEmpty(searchString))
            {
                data = _articleService.RetrieveAll()
                                        .Where(u => u.Title.Contains(searchString, StringComparison.OrdinalIgnoreCase))
                                        .Select(u => new ArticleViewModel
                                        {
                                            ArticleId = u.ArticleId,
                                            Title = u.Title,
                                            Body = u.Body,
                                            CategoryNavigation = u.CategoryNavigation,
                                            DateUpdated = u.DateUpdated,
                                        })
                                        .ToList();
            }

            var viewModel = new ArticleViewModel
            {
                Articles = data
            };
            return View(viewModel);
        }

        /// <summary>
        /// Return Article-Create View
        /// </summary>
        /// <returns></returns>
        [HttpGet ("/KnowledgeBase/Add-Article")]
        public IActionResult CreateModal()
        {
            var categories = _articleService.GetCategories()
                                   .Select(c => new SelectListItem
                                   {
                                       Value = c.CategoryId.ToString(),
                                       Text = c.CategoryName
                                   })
                                   .ToList();
            ViewBag.Categories = new SelectList(categories, "Value", "Text");

            return PartialView("CreateModal");
        }

        [HttpPost("/KnowledgeBase/Add-Article")]
        public IActionResult PostCreate(ArticleViewModel articleViewModel)
        {
            _articleService.Add(articleViewModel);
            return RedirectToAction("Index");
        }

        [HttpGet ("/KnowledgeBase/Article-Detail")]
        public IActionResult DetailModal(string articleId)
        {
            ViewBag.RoleId = _userRepository.GetUserById(_sessionHelper.GetUserIdFromSession()).RoleId;
            var articleData = _articleService.RetrieveAll().Where(a => a.ArticleId.ToString() == articleId).FirstOrDefault();
            var isFavorite = _favoriteRepository.RetrieveAll().Any(f => f.ArticleId.ToString() == articleId && f.UserId.ToString() == _sessionHelper.GetUserIdFromSession().ToString());
            if (articleData == null)
            {
                return NotFound();
            }

            var viewModel = new ArticleViewModel
            {
                ArticleId = articleId,
                Title = articleData.Title,
                Body = articleData.Body,
                UpdatedBy = articleData.UpdatedBy,
                DateUpdated = articleData.DateUpdated,
                IsFavorite = isFavorite,
            };

            return PartialView("DetailModal", viewModel);
        }

        [HttpGet("/KnowledgeBase/Article-Edit")]
        public IActionResult EditModal(string articleId)
        {
            var articleData = _articleService.RetrieveAll().Where(a => a.ArticleId.ToString() == articleId).FirstOrDefault();
            if (articleData == null)
            {
                return NotFound();
            }

            var viewModel = new ArticleViewModel
            {
                ArticleId = articleData.ArticleId,

ASI.Basecode.WebApp/Controllers/NotificationController.cs
using ASI.Basecode.Services.Interfaces;
using ASI.Basecode.Services.ServiceModels;
using ASI.Basecode.Services.Services;
using ASI.Basecode.WebApp.Mvc;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;

namespace ASI.Basecode.WebApp.Controllers
{
    public class NotificationController : ControllerBase<NotificationController>
    {
        private readonly INotificationService _notificationService;
        private readonly ITicketService _ticketService;
        private readonly ISessionHelper _sessionHelper;
        private readonly IUserService _userService;
        /// <param name = "httpContextAccessor" ></ param >
        /// <param name="loggerFactory"></param>
        /// <param name="configuration"></param>
        /// <param name="localizer"></param>
        /// <param name="mapper"></param>

        public NotificationController(
            INotificationService notificationService,
            ISessionHelper sessionHelper,
            ITicketService ticketService,
            IUserService userService,
            IHttpContextAccessor httpContextAccessor,
            ILoggerFactory loggerFactory,
            IConfiguration configuration,
            IMapper mapper = null) : base(httpContextAccessor, loggerFactory, configuration, mapper)
        {
            _notificationService = notificationService;
            _sessionHelper = sessionHelper;
            _ticketService = ticketService;
            _userService = userService;
        }

        /// <summary>
        /// Controller for index
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            var currentUser = _sessionHelper.GetUserIdFromSession().ToString();

            var data = _notificationService.RetrieveAll()
                .Where(u => u.RecipientId == currentUser)
                .Select(u => new NotificationServiceModel
                {
                    NotificationId = u.NotificationId,
                    Title = u.Title,
                    Body = u.Body,
                    TicketId = u.TicketId,
                    RecipientId = u.RecipientId,
                    DateCreated = u.DateCreated,
                    TicketNumber = u.TicketNumber,
                })
                .ToList();

            var userId = HttpContext.Session.GetString("UserId");
            if (string.IsNullOrEmpty(userId))
            {
                return RedirectToAction("Login", "Account");
            }

            var user = _userService.GetUserById(Guid.Parse(userId));
            if (user == null)
            {
                return NotFound();
            }

            var notifList = new NotificationServiceModel
            {
                UserNotifications = data
            };

            ViewBag.Role = user.RoleId;

            return View(notifList);
        }

        [HttpGet("/Notification/DetailModal")]
        public IActionResult DetailModal(string notificationId)
        {
            var data = _notificationService.RetrieveAll().Where(n => n.NotificationId == notificationId).FirstOrDefault();

            if (data == null)
            {
                return NotFound();
            }

            var viewModal = new NotificationServiceModel
            {
                NotificationId = data.NotificationId,
                Title = data.Title,
                Body = data.Body,
                TicketId = data.TicketId,
                RecipientId = data.RecipientId,
                DateCreated = data.DateCreated,
                TicketNumber = data.TicketNumber,
                TicketStatus = _ticketService.GetById(Guid.Parse(data.TicketId)).Status,
                AgentName = _ticketService.GetById(Guid.Parse(data.TicketId)).AgentName,
                RoleId = _userService.GetUserById(_sessionHelper.GetUserIdFromSession()).RoleId,
            };

            return PartialView("DetailModal", viewModal);
        }

        public IActionResult Notif()
        {
            return View();
        }
    }
}

ASI.Basecode.WebApp/Views/Shared/Admin_Header.cshtml
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor HttpContextAccessor
<div class="flex-Row justify-content-between py-2 px-5" style="border-bottom: 2px solid grey;">
    <div class="logosec hover-pointer">
        <img src="~/img/alliancedesk-logo.png"
             style="width: 185px;" alt="logo"
             onclick="window.location.href = '@Url.Action("Dashboard", "Admin")';">
    </div>
    
    <div class="logosec">
        <a asp-action="Index" asp-controller="Notification"><i class='bx bx-bell bx-sm bx-fw pt-1 mr-1 bell_icon' style="cursor: pointer; transform: scale(1.1); color: #45474B;"></i></a>

        <div class="btn-group">
            <img src="~/img/profile-logo.png" class="dpicn" data-bs-toggle="dropdown" aria-expanded="false" alt="Profile">
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#"><i class='bx bx-user'></i> Profile</a></li>
                <li><a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#settings" style="cursor: pointer;"><i class='bx bx-cog'></i> Settings</a></li>
                <li><a class="dropdown-item" asp-action="SignOutUser" asp-controller="Account"><i class='bx bx-log-out'></i> Logout</a></li>
            </ul>
        </div>
    </div>
</div>

@Html.Partial("/Views/User/SettingsModal.cshtml")

<script>
    const agentHeader = document.querySelector("[data-agent-header]")
    const agentSettings = document.querySelector("[data-agent-settings]")

    agentHeader.addEventListener("click", () => {
        agentSettings.classList.toggle("hidden")
    })
</script>

ASI.Basecode.WebApp/Views/Shared/Admin_Sidebar.cshtml
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor HttpContextAccessor
@section styles {
    <link rel="stylesheet" href="~/css/Admin.css" />
}
<div class="admin-sidebar flex flex-col gap-2 bg-White">   

    @if (ViewBag.AdminSidebar == "Overview")
    {
        <a asp-controller="Admin" data-td-none asp-action="Dashboard" data-admin-btn class=" admin-sb-active-button margin-0"><i class='bx bx-grid-alt bx-sm as' style="align-self:center;"></i>  <p>Overview</p> </a>
    }
    else
    {
        <a asp-controller="Admin" data-td-none asp-action="Dashboard" data-admin-btn class=" admin-sb-inactive-button margin-0"><i class='bx bx-grid-alt bx-sm as' style="align-self:center;"></i>  <p>Overview</p> </a>
    }
    @if (ViewBag.AdminSidebar == "Tickets") {
        <a asp-controller="Admin" data-td-none asp-action="Tickets" data-admin-btn class=" admin-sb-active-button margin-0"><i class='bx bx-purchase-tag-alt bx-sm as' style="align-self:center;"></i> <p>Tickets</p> </a>
    } else { 
        <a asp-controller="Admin" data-td-none asp-action="Tickets" data-admin-btn class=" admin-sb-inactive-button margin-0"><i class='bx bx-purchase-tag-alt bx-sm as' style="align-self:center;"></i> <p>Tickets</p> </a>
    } 
    @if (ViewBag.AdminSidebar == "ViewUser")
    {
        <a asp-controller="Admin" data-td-none asp-action="ViewUser" data-admin-btn class=" admin-sb-active-button margin-0"><i class='bx bx-group bx-sm as' style="align-self:center;"></i> <p>Directory</p> </a>
    }
    else
    {
        <a asp-controller="Admin" data-td-none asp-action="ViewUser" data-admin-btn class=" admin-sb-inactive-button margin-0"><i class='bx bx-group bx-sm as' style="align-self:center;"></i> <p>Directory</p> </a>
    }
    @if (ViewBag.AdminSidebar == "Index")
    {
        <a asp-controller="Article" data-td-none asp-action="Index" data-admin-btn class=" admin-sb-active-button margin-0"><i class="bx bx-news" style="align-self:center; margin-right: 1rem;"></i> <p>Knowledge Base</p> </a>
    }
    else
    {
        <a asp-controller="Article" data-td-none asp-action="Index" data-admin-btn class=" admin-sb-inactive-button margin-0"><i class="bx bx-news" style="align-self:center; margin-right: 1rem;"></i> <p>Knowledge Base</p> </a>
    }
    
    @if (ViewBag.AdminSidebar == "Analytics")
    {
        <a asp-controller="Admin" data-td-none asp-action="AnalyticsOverallMetrics" data-admin-btn class=" admin-sb-active-button margin-0"><i class='bx bx-objects-vertical-bottom bx-sm as' style="align-self:center;"></i> <p>Analytics</p> </a>
    }
    else
    {
        <a asp-controller="Admin" data-td-none asp-action="AnalyticsOverallMetrics" data-admin-btn class=" admin-sb-inactive-button margin-0"><i class='bx bx-objects-vertical-bottom bx-sm as' style="align-self:center;"></i> <p>Analytics</p> </a>
    }
    
        
    
</div>

<script>
    // Function to handle toggle button active-inactive states
        document.addEventListener('DOMContentLoaded', function () {
        var buttons = document.querySelectorAll('[data-admin-btn]');

        buttons.forEach(function (button) {
            button.addEventListener('click', function () {
                if (this.classList.contains('admin-sb-active-button')) {
                    // If the button is already active, do nothing (toggle off)
                    return;
                }

                // Remove active state from all buttons
                buttons.forEach(function (btn) {
                    btn.classList.remove('admin-sb-active-button');
                    btn.classList.add('admin-sb-inactive-button');
                });

                // Set this button as active
                this.classList.remove('admin-sb-inactive-button');
                this.classList.add('admin-sb-active-button');
            });
        });
    }); 

</script>

ASI.Basecode.WebApp/Views/Shared/Agent_Admin_Header.cshtml
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor HttpContextAccessor
<header>
    <div class="logosec hover-pointer">
        <img src="~/img/alliancedesk-logo.png"
             style="width: 185px;" alt="logo"
             onclick="window.location.href = '@Url.Action("Index", "Home")';">
    </div>
    
    <div class="logosec">        
        <i class='bx bx-bell bx-sm' style="color: #45474B; cursor: pointer;"></i>
        <i class='bx bx-cog bx-sm' style="color: #45474B; cursor: pointer;"></i>

        <div class="mr-20 hover-pointer" style="position: relative">           

            <div class="dp">                                
                <img src="~/img/profile-logo.png" class="dpicn hover-pointer" alt="dp">           
            </div>

            <div class="dropdown">
                <ul>                    
                    <li>
                        <i class="bx bx-user bx-xs bx-fw" style="color: #3D3B40;"></i>
                        <a href="#">Profile</a>
                    </li>
                    <li>
                        <i class="bx bx-log-out bx-xs bx-fw" style="color: #3D3B40;"></i>
                        <a asp-action="SignOutUser" asp-controller="Account">Logout</a>
                    </li>
                </ul>
            </div>

        </div>
    </div>
</header>

ASI.Basecode.WebApp/Views/Shared/Agent_Header.cshtml
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor HttpContextAccessor
<div class="flex-Row justify-content-between py-2 px-5" style="border-bottom: 2px solid grey;">
    <div class="logosec hover-pointer">
        <img src="~/img/alliancedesk-logo.png"
             style="width: 185px;" alt="logo"
             onclick="window.location.href = '@Url.Action("Dashboard", "Agent")';">
    </div>
    
    <div class="logosec flex-Row align-items-center justify-content-center">
        <a asp-action="Index" asp-controller="Notification"><i class='bx bx-bell bx-sm bx-fw pt-1 mr-1 bell_icon' style="cursor: pointer; transform: scale(1.1); color: #45474B;"></i></a>

        <div class="btn-group">
            <img src="~/img/profile-logo.png" class="dpicn" data-bs-toggle="dropdown" aria-expanded="false" alt="Profile">
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#"><i class='bx bx-user'></i> Profile</a></li>
                <li><a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#settings" style="cursor: pointer;"><i class='bx bx-cog'></i> Settings</a></li>
                <li><a class="dropdown-item" asp-action="SignOutUser" asp-controller="Account"><i class='bx bx-log-out'></i> Logout</a></li>
            </ul>
        </div>
        @* <i class='bx bx-cog bx-sm' style="color: #45474B; cursor: pointer;"></i>

        <div class="mr-20 hover-pointer" style="position: relative">           

            <div data-agent-header class="dp">
                <img src="~/img/profile-logo.png" class="dpicn hover-pointer" alt="dp">           
            </div>

            <div data-agent-settings class="hidden absolute" style="top:2rem; left:-5rem; background: white; z-index: 100; border: 1px solid black; border-radius: 3px; padding: 0.5rem 1rem;">
                           
                    <div>
                        <a asp-action="AgentProfile" asp-controller="Agent" class="flex flex-Row align-items-center gap-2">
                            <i class="bx bx-user bx-xs bx-fw" style="color: #3D3B40;"></i>
                            <p class="text-black-50">Profile</p>
                            </a>
                    </div>
                    <div>
                        <i class="bx bx-log-out bx-xs bx-fw" style="color: #3D3B40;"></i>
                    <a asp-action="SignOutUser" asp-controller="Account" class="text-black-50">Logout</a>
                    </div>
               
            </div>

        </div> *@
    </div>
</div>

@Html.Partial("/Views/User/SettingsModal.cshtml")

<script>
    const agentHeader = document.querySelector("[data-agent-header]")
    const agentSettings = document.querySelector("[data-agent-settings]")

    agentHeader.addEventListener("click", () => {
        agentSettings.classList.toggle("hidden")
    })
</script>

ASI.Basecode.WebApp/Views/Shared/Agent_Sidebar.cshtml
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor HttpContextAccessor

@{
    // Set default value if ViewData["AgentSidebar"] is null
    var currentSidebar = ViewData["AgentSidebar"]?.ToString() ?? "Overview";
}
@section styles {
    <link rel="stylesheet" href="~/css/Admin.css" />
}

<div class="admin-sidebar flex flex-col gap-2 bg-White">

    @if (ViewData["AgentSidebar"].Equals("Overview"))
    {
        <a asp-controller="Agent" data-td-none  asp-action="Dashboard" data-admin-btn class=" admin-sb-active-button margin-0"><i class='bx bx-grid-alt bx-sm as' style="align-self:center;"></i>  <p>Overview</p> </a>
    }
    else
    {
        <a asp-controller="Agent" data-td-none asp-action="Dashboard" data-admin-btn class=" admin-sb-inactive-button margin-0"><i class='bx bx-grid-alt bx-sm as' style="align-self:center;"></i>  <p>Overview</p> </a>
    }
 
    @if ((ViewData["AgentSidebar"].Equals("ViewUser")))
    {
        <a asp-controller="Agent" data-td-none asp-action="Teams" data-admin-btn class=" admin-sb-active-button margin-0"><i class='bx bx-group bx-sm as' style="align-self:center;"></i> <p>Teams</p> </a>
    }
    else
    {
        <a asp-controller="Agent" data-td-none asp-action="Teams" data-admin-btn class=" admin-sb-inactive-button margin-0"><i class='bx bx-group bx-sm as' style="align-self:center;"></i> <p>Teams</p> </a>
    }
    @if (ViewData["AgentSidebar"].Equals("Index"))
    {
        <a asp-controller="Article" data-td-none asp-action="Index" data-admin-btn class=" admin-sb-active-button margin-0"><i class="bx bx-news" style="align-self:center; margin-right: 1rem;"></i> <p>Knowledge Base</p> </a>
    }
    else
    {
        <a asp-controller="Article" data-td-none asp-action="Index" data-admin-btn class=" admin-sb-inactive-button margin-0"><i class="bx bx-news" style="align-self:center; margin-right: 1rem;"></i> <p>Knowledge Base</p> </a>
    }

</div>

<script>
    // Function to handle toggle button active-inactive states
    document.addEventListener('DOMContentLoaded', function () {
        var buttons = document.querySelectorAll('[data-admin-btn]');

        buttons.forEach(function (button) {
            button.addEventListener('click', function () {
                if (this.classList.contains('admin-sb-active-button')) {
                    // If the button is already active, do nothing (toggle off)
                    return;
                }

                // Remove active state from all buttons
                buttons.forEach(function (btn) {
                    btn.classList.remove('admin-sb-active-button');
                    btn.classList.add('admin-sb-inactive-button');
                });

                // Set this button as active
                this.classList.remove('admin-sb-inactive-button');
                this.classList.add('admin-sb-active-button');
            });
        });
    });

</script>

ASI.Basecode.WebApp/Views/Shared/General_Header.cshtml
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor HttpContextAccessor
<div class="flex-Row justify-content-between py-2 px-5" style="border-bottom: 2px solid grey;">
    <div class="logosec hover-pointer">
        <img src="~/img/alliancedesk-logo.png"
             style="width: 185px;" alt="logo"
             onclick="window.location.href = '@Url.Action("Index", "Account")';">
    </div>
    <div class="logosec">
        <!--- @HttpContextAccessor.HttpContext.Session.GetString("UserName") -->
        <div class="mr-20 hover-pointer" style="position: relative">
            @* <a asp-controller="Account" data-td-none asp-action="Register" class="registerBtn">Register</a> *@
            <a asp-controller="Account" data-td-none asp-action="Login" class="btn btn-danger admin-sb-active-button px-3 py-1">Login</a>
            </div>
            <div class="dropdown">
                <ul>
                    <li>
                        <i class="fa-solid fa-gear"></i>
                        <a href="#">Settings</a>
                    </li>
                    <li>
                        <i class="fa-solid fa-right-from-bracket"></i>
                        <a asp-action="SignOutUser" asp-controller="Account">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

ASI.Basecode.WebApp/Views/Shared/User_Header.cshtml
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor HttpContextAccessor

@section styles {
    <link rel="stylesheet" href="~/css/user_tickets.css" />
}

<header>
    <div class="logo">
        <img src="~/img/alliancedesk-logo.png" style="width: 185px;" alt="logo" onclick="window.location.href = '@Url.Action("Index", "Home")';">
    </div>

    <div class="header-buttons">
        <button type="button" class="btn button" data-bs-toggle="modal" data-bs-target="#createTicket"><i class='bx bx-plus-circle bx-xs bx-fw uh' style="align-self:center;"></i> Create Ticket </button>
        <a asp-action="Index" asp-controller="Notification"><i class='bx bx-bell bx-sm icon' style="color: #45474B; cursor: pointer;"></i></a>
        <i class='bx bx-cog bx-sm icon' style="color: #45474B; cursor: pointer;" data-bs-toggle="modal" data-bs-target="#settings"></i>

        <div class="dropdown">
            <a class="profile dropdown-toggle" href="#" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="~/img/profile-logo.png" class="dpicn hover-pointer" alt="dp">
            </a>

            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <li>
                    <a class="dropdown-item" href="#"><i class="bx bx-user bx-xs bx-fw" style="color: #3D3B40;"></i> Profile</a>
                </li>
                <li>
                    <a class="dropdown-item" asp-action="SignOutUser" asp-controller="Account"><i class="bx bx-log-out bx-xs bx-fw" style="color: #3D3B40;"></i> Logout</a>
                </li>
            </ul>
        </div>
    </div>
</header>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var dpIcon = document.querySelector('.dpicn');
        var dropdownMenu = document.getElementById('dropdownMenu');

        dpIcon.addEventListener('click', function (event) {
            event.stopPropagation();

            if (dropdownMenu.style.display === 'block') {
                dropdownMenu.style.display = 'none';
            } else {
                dropdownMenu.style.display = 'block';
            }
        });
    });

</script>